version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"

  phpunit:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - app
    command: vendor/bin/phpunit
